export const mockStudents = [
  {
    id: "1",
    name: "Sophie Martin",
    email: "sophie.martin@email.com",
    field: "Développement React Senior - Technologie",
    matchingScore: 87,
    status: "premium",
    joinDate: "2024-01-15",
    avatar: "/placeholder.svg",
    phone: "+33 6 12 34 56 78",
    location: "Paris, France",
    experience: "5 ans",
    skills: ["React", "TypeScript", "Node.js"],
  },
  {
    id: "2",
    name: "Jean Martin",
    email: "jean.martin@email.com",
    field: "Data Scientist - Analyse",
    matchingScore: 84,
    status: "active",
    joinDate: "2024-02-10",
    avatar: "/placeholder.svg",
    phone: "+33 6 98 76 54 32",
    location: "Lyon, France",
    experience: "3 ans",
    skills: ["Python", "Machine Learning", "SQL"],
  },
  {
    id: "3",
    name: "Marie Dubois",
    email: "marie.dubois@email.com",
    field: "UX/UI Designer - Design",
    matchingScore: 91,
    status: "premium",
    joinDate: "2024-01-28",
    avatar: "/placeholder.svg",
    phone: "+33 6 11 22 33 44",
    location: "Marseille, France",
    experience: "4 ans",
    skills: ["Figma", "Adobe XD", "Prototyping"],
  },
  {
    id: "4",
    name: "Pierre Laurent",
    email: "pierre.laurent@email.com",
    field: "DevOps Engineer - Infrastructure",
    matchingScore: 89,
    status: "active",
    joinDate: "2024-03-05",
    avatar: "/placeholder.svg",
    phone: "+33 6 55 66 77 88",
    location: "Toulouse, France",
    experience: "6 ans",
    skills: ["Docker", "Kubernetes", "AWS"],
  },
  {
    id: "5",
    name: "Lucas Rousseau",
    email: "lucas.rousseau@email.com",
    field: "Marketing Digital - Marketing",
    matchingScore: 76,
    status: "active",
    joinDate: "2024-02-20",
    avatar: "/placeholder.svg",
    phone: "+33 6 99 88 77 66",
    location: "Nantes, France",
    experience: "2 ans",
    skills: ["SEO", "Google Ads", "Analytics"],
  },
]

export const mockCompanies = [
  {
    id: "1",
    name: "TechCorp Solutions",
    sector: "Technologie",
    employees: 250,
    location: "Paris, France",
    activeJobs: 12,
    candidates: 1247,
    status: "active",
    joinDate: "2023-06-15",
    logo: "/placeholder.svg",
    description: "Entreprise leader en solutions technologiques",
  },
  {
    id: "2",
    name: "Digital Marketing Pro",
    sector: "Marketing",
    employees: 85,
    location: "Lyon, France",
    activeJobs: 5,
    candidates: 456,
    status: "active",
    joinDate: "2023-08-20",
    logo: "/placeholder.svg",
    description: "Agence de marketing digital innovante",
  },
  {
    id: "3",
    name: "Green Energy Corp",
    sector: "Énergie",
    employees: 180,
    location: "Marseille, France",
    activeJobs: 8,
    candidates: 789,
    status: "premium",
    joinDate: "2023-05-10",
    logo: "/placeholder.svg",
    description: "Solutions d'énergie renouvelable",
  },
]

export const mockJobs = [
  {
    id: "1",
    title: "Développeur React Senior",
    company: "TechCorp Solutions",
    location: "Paris, France",
    type: "CDI",
    salary: "55k-70k €",
    applicants: 45,
    status: "active",
    publishDate: "2024-01-10",
    description: "Recherche développeur React expérimenté",
    requirements: ["React", "TypeScript", "5+ ans d'expérience"],
  },
  {
    id: "2",
    name: "Digital Product Marketing Manager",
    company: "Digital Marketing Pro",
    location: "Lyon, France",
    type: "CDI",
    salary: "45k-55k €",
    applicants: 32,
    status: "active",
    publishDate: "2024-01-15",
    description: "Manager marketing produit digital",
    requirements: ["Marketing", "Product Management", "3+ ans"],
  },
  {
    id: "3",
    title: "Ingénieur DevOps",
    company: "Green Energy Corp",
    location: "Marseille, France",
    type: "CDI",
    salary: "50k-65k €",
    applicants: 28,
    status: "urgent",
    publishDate: "2024-01-20",
    description: "Ingénieur DevOps pour infrastructure cloud",
    requirements: ["Docker", "Kubernetes", "AWS", "4+ ans"],
  },
]

export const mockApplications = [
  {
    id: "1",
    candidateName: "Marie Dubois",
    candidateEmail: "marie.dubois@email.com",
    jobTitle: "Développeur Frontend React",
    company: "TechCorp Solutions",
    status: "en_attente",
    score: 87,
    appliedDate: "2024-01-15",
    avatar: "/placeholder.svg",
  },
  {
    id: "2",
    candidateName: "Pierre Martin",
    candidateEmail: "pierre.martin@email.com",
    jobTitle: "Data Scientist Senior",
    company: "DataCorp",
    status: "approuve",
    score: 92,
    appliedDate: "2024-01-10",
    avatar: "/placeholder.svg",
  },
  {
    id: "3",
    candidateName: "Sophie Bernard",
    candidateEmail: "sophie.bernard@email.com",
    jobTitle: "UX/UI Designer",
    company: "DesignStudio",
    status: "en_cours",
    score: 88,
    appliedDate: "2024-01-12",
    avatar: "/placeholder.svg",
  },
  {
    id: "4",
    candidateName: "Lucas Rousseau",
    candidateEmail: "lucas.rousseau@email.com",
    jobTitle: "DevOps Engineer",
    company: "CloudTech",
    status: "rejete",
    score: 75,
    appliedDate: "2024-01-08",
    avatar: "/placeholder.svg",
  },
]

export const mockUsers = [
  {
    id: "1",
    name: "Sophie Martin",
    email: "sophie.martin@goriya.com",
    role: "Candidat",
    status: "Actif",
    joinDate: "2024-01-15",
    lastLogin: "2024-01-20",
    references: "Super CV 95/100",
  },
  {
    id: "2",
    name: "Jean Dubois",
    email: "jean.dubois@techcorp.com",
    role: "Entreprise",
    status: "Actif",
    joinDate: "2023-12-01",
    lastLogin: "2024-01-19",
    references: "12 offres",
  },
  {
    id: "3",
    name: "Marie Laurent",
    email: "marie.laurent@goriya.com",
    role: "Candidat",
    status: "Inactif",
    joinDate: "2024-01-10",
    lastLogin: "2024-01-18",
    references: "Score CV 72/100",
  },
  {
    id: "4",
    name: "Vincent SARL",
    email: "contact@vincent-sarl.com",
    role: "Entreprise",
    status: "Actif",
    joinDate: "2023-11-15",
    lastLogin: "2024-01-20",
    references: "8 offres",
  },
]

export const mockPortfolios = [
  {
    id: "1",
    candidateName: "Sophie Martin",
    title: "Portfolio Développeur Frontend",
    views: 1247,
    likes: 89,
    projects: 5,
    skills: ["React", "TypeScript", "CSS"],
    image: "/placeholder.svg",
    description: "Portfolio complet avec projets React",
  },
  {
    id: "2",
    candidateName: "Jean Dubois",
    title: "Data Science Projects",
    views: 856,
    likes: 67,
    projects: 3,
    skills: ["Python", "ML", "Pandas"],
    image: "/placeholder.svg",
    description: "Projets d'analyse de données et ML",
  },
  {
    id: "3",
    candidateName: "Marie Laurent",
    title: "UX/UI Design Showcase",
    views: 1456,
    likes: 123,
    projects: 8,
    skills: ["Figma", "Adobe XD", "Prototyping"],
    image: "/placeholder.svg",
    description: "Showcase de designs UX/UI innovants",
  },
]

export const mockEvents = [
  {
    id: "1",
    title: "Entretien RH - Sophie Martin",
    type: "entretien",
    date: "2024-01-16",
    time: "14:00",
    duration: "1h",
    status: "confirme",
    participants: ["Sophie Martin", "RH Manager"],
  },
  {
    id: "2",
    title: "Session Formation IA - Groupe A",
    type: "formation",
    date: "2024-01-16",
    time: "16:30",
    duration: "2h",
    status: "programme",
    participants: ["Groupe A", "Formateur IA"],
  },
  {
    id: "3",
    title: "Réunion équipe recrutement",
    type: "reunion",
    date: "2024-01-17",
    time: "10:00",
    duration: "1h30",
    status: "confirme",
    participants: ["Équipe RH"],
  },
]
